### ISSUE TITLE
Error: Transcript is disabled on this video when running in a Codespace

### ISSUE THREAD

**Issue by DanWahlin** [Azure-Samples/langchainjs-quickstart-demo#4]
Trying to run this in a codespace (successfully installed and ran ollama there) but get the following error. I changed it to a personal video that I know also has a transcript but get the same error. Tried updating packages to the latest versions but the error persists so I'm wondering if it's a codespaces limitation?

```
➜ /workspaces/langchainjs-quickstart-demo (main) $ npm run start:local

> langchainjs-quickstart-demo@1.0.0 start:local
> node src/local.js

Loading documents...
file:///workspaces/langchainjs-quickstart-demo/node_modules/@langchain/community/dist/document_loaders/web/youtube.js:97
            throw new Error(`Failed to get YouTube video transcription: ${e.message}`);
                  ^

Error: Failed to get YouTube video transcription: [YoutubeTranscript] 🚨 Transcript is disabled on this video (u0AUwOKxUsg)
    at YoutubeLoader.load (file:///workspaces/langchainjs-quickstart-demo/node_modules/@langchain/community/dist/document_loaders/web/youtube.js:97:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///workspaces/langchainjs-quickstart-demo/src/local.js:22:22
```

**Comment by sinedied** [comment]
I reproduced the issue on Codespaces, but locally it worked. Looking through GH issues, it may be because [Google bans some IPs due to to web scraping](https://github.com/Kakulukian/youtube-transcript/issues/11#issuecomment-2244224076). 

I've sent an upstream PR to Langchain hoping to solve this using a package relying on YT inner API instead of web scraping: https://github.com/langchain-ai/langchainjs/pull/7477
